#!/bin/bash
# This script installs Docker on Ubuntu 22.04 LTS

sudo apt update;
sudo apt install ca-certificates curl gnupg -y;

sudo install -m 0755 -d /etc/apt/keyrings;

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg || { echo "Failed to download or process the GPG key"; exit 1; };

sudo chmod a+r /etc/apt/keyrings/docker.gpg
