version: '3'
services:
  api:
    build: ./api
    expose:
      - "5000"
    environment:
      - TZ=America/New_York # You can change this to your preferred timezone, e.g., "America/New_York"
    volumes:
      - ./api:/app  # Optional: For development to see changes without rebuilding

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api